### ISSUE TITLE
Harmonise linter with styler

### ISSUE THREAD

**Issue by josephguillaume** [josephguillaume/hydromad#102] opened 2020-07-01 01:02 UTC
Lintr requires changes that styler should ideally address, and that we might not want contributors to have to deal with manually.

**Comment by josephguillaume** [comment] 2020-07-01 01:03
##[warning]Opening curly braces should never go on their own line and should always be followed by a new line.

**Comment by josephguillaume** [comment] 2020-07-01 01:29
@mortisflux - you're probably most familiar with how we turn off these settings in the lintr? Or turn them on in styler #100?

**Comment by jnothman** [comment] 2020-07-01 03:50
Line length can be hard for an auto-formatter to address sometimes. I'm a bit surprised that the whitespace-around-commas/parentheses issues weren't fixed by styler.

**Comment by jnothman** [comment] 2020-07-01 03:52
Is it possible that these were not addressed because you did not apply Styler to those files, but only the ones in the package itself? The failures I see in Annotations are in inst/doc/hydromad_results.R

**Comment by josephguillaume** [comment] 2020-07-01 04:37
I'll have a look at that - I just used style_pkg, and I think it did indeed only touch files in the R/ folder

**Comment by mortisflux** [comment] 2020-07-01 04:53
@jnothman I think you're correct, `styler::style_pkg()` formats source files (i.e. mostly files in the R folder).`styler::style_dir()` can be implemented to style R files within another directory.

> how we turn off these settings in the lintr? Or turn them on in styler?

We should be able to turn off some of these settings off for lintr with something like this:

```
lintr::lint_package(linters = lintr::with_defaults( 
  object_name_linter = NULL,  # prevents linting object names  
  commas_linter = NULL,  # prevents linting spaces before commas  
  trailing_whitespace_linter = NULL, # prevents trailing whitespace linting
  line_length_linter = NULL, # prevents line length linting
  open_curly_linter = NULL # prevents linting of curly braces openings on new line
)  
```

More options for disabling particular linters can be found [here](https://github.com/jimhester/lintr).

The basic options for styler use the `scope` and `strict` options. `scope = "spaces"` will style the whitespace between tokens (characters, numbers, symbols, etc), whilst `scope = tokens` is a bit more [invasive](https://www.tidyverse.org/blog/2017/12/styler-1.0.0/). `strict = TRUE` sets whitespace around tokens and punctuation to either 0 or 1. I think we're after a finer level of control here, so what might be a better option going forward is to create a [custom](https://www.r-bloggers.com/customizing-styler-the-quick-way/) [styler](https://styler.r-lib.org/articles/customizing_styler.html) (the default is tidyverse).

**Comment by jnothman** [comment] 2020-07-01 04:56
Of those, I'd only really want to disable `object_name_linter`, and make exceptions for line length only in specific cases.

**Comment by jnothman** [comment] 2020-07-01 04:57
I don't think @josephguillaume has a problem with the whitespace cleaning, but was perhaps confused because lintr got upset about things that styler was meant to have fixed.

**Comment by josephguillaume** [comment] 2020-07-01 05:31
Yeah, I checked the files ignoring changes in whitespace - I'm quite happy with it.
Let's see which of these are left after I check the R files outside the R/ folder.

**Comment by josephguillaume** [comment] 2020-07-01 07:05
Looks like it wasn't just that.

This gets annotated with: "Place a space before left parenthesis, except in a function call."
I would agree with styler that this shouldn't change.
```R
    shape = 2^(-1:5), ## use discrete values of shape on log scale, for simulation
```
https://github.com/josephguillaume/hydromad/blob/master/inst/doc/hydromad_results.R#L9

Given the limited number of annotation shown, it's a bit tricky finding other examples.

**Comment by mortisflux** [comment] 2020-07-02 06:57
> This gets annotated with: "Place a space before left parenthesis, except in a function call."
> I would agree with styler that this shouldn't change.
> 
> ```r
>     shape = 2^(-1:5), ## use discrete values of shape on log scale, for simulation
> ```

Hmm, I see what you mean about the discrepancies ... that is a not so great suggestion from lintr.

> Of those, I'd only really want to disable `object_name_linter`, and make exceptions for line length only in specific cases.

Though if we're operating under the assumption that styler gives us most of the formatting we want, we do need to tweak some linters so that the two won't clash. Maybe not the ones I suggested previously, but others listed in the [documentation](https://cran.r-project.org/web/packages/lintr/lintr.pdf). First, I'd recommend we be sure about the style we want to use #100 and then see how we can get lintr to play nicely with the style of choice. 

We could also consider coding in some no-lint areas within .R files using `# nolint start` and`# nolint end` around specific blocks of text. Cons: there are quite a few .R files in hydromad, and going through each and every one of these would be a pain, so this may not be the best option, but could work for some select examples if lintr/styler still won't cooperate properly.

**Comment by jnothman** [comment] 2020-07-02 12:48
Per https://style.tidyverse.org/syntax.html#infix-operators, I think lintr's handling of `^` (exponent operator) before parentheses is a bug (per https://style.tidyverse.org/syntax.html#infix-operators) and should be raised in their issue tracker. As you can see in Hadley's guide, other high-precedence operators do not tend to have generic expressions on their right hand side, so it's probably an omission from lintr's test suite. I get the same issue with `-(a + b)` which it wants me to correct to `- (a + b)`.

Who wants to [open an issue at lintr](https://github.com/jimhester/lintr/issues/new)?

Practically, we can disable all lintr checks regarding whitespace. That's styler's job.

**Comment by mortisflux** [comment] 2020-07-03 01:01
I'll open an issue.

Looks like there have been a number of similar-ish issues with lintr and parentheses (though with a "((" rather than with an infix operator):
[https://github.com/jimhester/lintr/issues/259](https://github.com/jimhester/lintr/issues/259)
[https://github.com/jimhester/lintr/issues/77](https://github.com/jimhester/lintr/issues/77)

**Comment by jnothman** [comment] 2020-07-03 03:53
Indeed. The unary operators may not yet have been flagged (perhaps because parentheses are not often used after unary `-`).

I am not very persuaded by the testing regime in lintr. For instance, https://github.com/jimhester/lintr/commit/3a26dc714f08bdc97c20541ecfab7663b7a6c62e stops checking that `^` requires spaces around it, but does not ensure non-regression of `^` followed by parentheses.
I'd therefore still support switching off stylistic checks in lintr, and allow it to focus on other code smells.

**Comment by mortisflux** [comment] 2020-07-07 05:03
I've taken a look at which linters need to be switched off so that it stops focusing on things that styler has already fixed. My suggestion is:

```
lintr::lint_package(linters = lintr::with_defaults(
	object_name_linter = NULL, 
	object_length_linter = NULL,
	object_usage_linter = NULL, #(addresses #105 and #106)
	spaces_left_parentheses_linter = NULL,
	spaces_inside_linter = NULL,
	open_curly_linter = NULL,
	line_length_linter = NULL,
	commented_code_linter = NULL, # otherwise lintr asks that you remove comments
	paren_brace_linter = NULL,
	trailing_whitespace_linter = NULL,
	trailing_blank_lines_linter = NULL,
	commas_linter = NULL
	))

```

The above should stop lintr from trying to correct styler's changes. After linting the whole package its warnings are now for:
- Cyclomatic complexity (#107)
- Avoid 1:ncol/nrow/length(...) expressions (#103)

Let me know if you think [other linters](https://github.com/jimhester/lintr) should be included, though it seems that the remainder of the stylistic linters don't clash with styler's current formatting (e.g. `assignment_linter` and `no_tab_linter`). If everyone is happy with this, I'll open a PR to update lintr.

**Comment by jnothman** [comment] 2020-07-07 06:30
Several of those are "things we don't want to deal with yet" like object name, object length. Object usage is worth resolving IMO, by installing dependencies before linting. It can identify substantive issues when test coverage is not 100%. I think you're right that they can be disabled for now, but issues like #105, #106 and maybe #104 should be resolved and those linters turned back on when you do so.

**Comment by jnothman** [comment] 2020-07-07 06:31
I think the same is true of cyclomatic complexity and perhaps `1:ncol`: disable them for now, and turn each one on when ready.

**Comment by mortisflux** [comment] 2020-07-07 22:44
> Object usage is worth resolving IMO, by installing dependencies before linting. It can identify substantive issues when test coverage is not 100%. 

I agree, though `R CMD check` also flags this, so @josephguillaume suggested disabling this check in lintr (#105).

**Closed** 2020-07-12 02:45 UTC
Labels: github

**Comment by josephguillaume** [comment] 2020-07-12 02:58
Thanks!
